VolteraInc/ink-database

pastes/WickedWasp.json

add Paste WickedWasp

---

pastes/YappyYellowjacket.json

Add YappyYellowjacket

---

inks/BossyBass.json

Beware! first ink made from webapp

add flex BossyBass

---

pastes/ZootyZorapetra.json

Add ZootyZorapetra

---

pastes/ZootyZoraptera.json

ZootyZorapetra -> ZootyZoraptera

spelling mistake

---

pastes/BrilliantBeetle.json
pastes/YouthfulYuhina.json
pastes/ZippyZebradove.json

Solder Paste T4 Bi
- Add YouthfulYuhina
- Add ZippyZebradove
note: Same batch different Lot #
Solder Paste T5 Bi
-Add BrilliantBeetle

YouthfulYuhina, ZippyZebradove, BrilliantBeetle

---

pastes/ComicalCicada.json
pastes/KindredKoala.json

T5 Bi Solder Paste
-ComicalCicada
T5 Pb Solder Paste
-KindredKoala

Add ComicalCicada, KindredKoala

---

inks/DynamicDolphin.json
inks/RomanticRaiju.json
pastes/AmusedAuklet.json

DynamicDolphin - Flex2
RomanticRaiju - Cond2
AmusedAuklet - T4 Bi

Add DynamicDolphin, RomanticRaiju, AmusedAuklet

---

pastes/DivineDragonfly.json

- Add DivineDragonfly (T5 Solder Paste Bi)

Add DivineDragonfly

---

pastes/FieryFirefly.json
pastes/GiddyGrasshopper.json

GiddyGrasshopper (Solder Paste T5 Bi)

Added GiddyGrasshopper

---

pastes/HappyHoneybee.json

- HappyHoneybee (SolderPaste T5)

Added HappyHoneybee

---

pastes/IcyInchworm.json
pastes/MightyMouse.json

-IcyInchworm (Solder Paste SnBiAg1)
-MightyMouse (Solder Paste Sn63)

Added IcyInchworm and MightyMouse

---

pastes/JovialJunebug.json

-JovialJunebug (SolderPaste T5 Bi)

Added JovialJunebug

---

pastes/KeenKatydid.json

- KeenKatydid (Solder Paste T5 Bi)

Added KeenKatydid

---

inks/BionicBorg.json

Added Conductive 3
- BionicBorg

Added BionicBorg

---

pastes/ElegantEmu.json

- ElegantEmu (Solder Paste T4)

Added ElegantEmu

---

pastes/LoudLocust.json
pastes/NobleNarwhal.json

Added LoudLocust Solder Paste T5(SnBiAg1)
Added NobleNarwhal Solder Paste T5 (Lead SN63)

Added LoudLocust & NobleNarwhal

---

pastes/MarvelMantis.json

- MarvelMantis (SnBiAg1 T5 Solder Paste)

Added MarvelMantis

---

inks/ChattyCerberus.json
pastes/FunkyFalcon.json

-ChattyCerberus (Conductive3)
-FunkyFalcon (SolderPaste T4)

Added ChattyCerberus and FunkyFalcon

---

pastes/KeenKatydid.json
pastes/LoudLocust.json
pastes/MarvelMantis.json

- Replaced the mentioned pastes with the correct .json files. From SolderPaste into SolderPaste T5

Replaced KeenKatydid, LoudLocust and MarvelMantis with the right files.

---

pastes/NosyNightcrawler.json
pastes/OutgoingOtter.json

Added
- NosyNightcrawler Solder Paste T5 (SnBiAg1)
- OutgoingOtter Solder Paste T5 (Lead, Sn63)

Added NosyNightcrawler and OutgoingOtter

---

inks/DapperDrider.json
pastes/PoisedPickleworm.json

Added
- Cond3 Ink DapperDriver
- T5 Solder Paste PoisedPickleworm

Added Cond3 Ink DapperDrider & T5 Solder Paste PoisedPickleworm

---

inks/ChattyCerberus.json
inks/DapperDrider.json

- Changed ChattyCerberus Temp - From 120C into 170C for 15mins
- Changed DapperDrider Temp - From 120C into 170C for 15mins

Changed Heating Profile settings based on Tom Pol's QC

---

pastes/GeekyGrackle.json

- Added T4 Solder Paste GeekyGrackle

Added GeekyGrackle T4 Solder Paste

---

pastes/RoyalRobberFly.json

- RoyalRobberFly (SnBiAg1 - T5)

Added RoyalRobberFly

---

inks/AffableAlien.json
inks/BionicBorg.json
inks/ChattyCerberus.json
inks/DapperDrider.json

Heating Profile values was incorrect and was copy/pasted incorrectly starting from AffableAlien up to DapperDrider.
Ink Profile that were changed:
- AffableAlien
- BionicBorg
- ChattyCerberus
- DapperDrider

Updating heating profile values

---

pastes/PallyPlatypus.json

Added PallyPlatypus Sn63 Lead Solder Paste

Added PallyPlatypus

---

pastes/SpiritedSilverfish.json

- Added SpiritedSilverfish (SnBiAg1 - T5)

Added SpritedSilverfish

---

inks/ElatedEywa.json

Added ElatedEywa (Conductive 3)

Added ElatedEywa

---

pastes/QuirkyQuokka.json
pastes/TranquilThrips.json

Added Solder Paste
- TranquilThrips (SnBiAg1) - T5
- QuirkyQuokka (Lead, Sn63) - T5

Added TranquilThrips & QuirkyQuokka

---

pastes/Inspiring'I'iwi.json

Added SolderPaste T4
- Inspring'I'iwi

Added Inspring'I'iwi

---

pastes/ViableVirbiamoth.json

Added T5 SolderPaste
-ViableVirbiamoth

Added ViableVirbiamoth

---

inks/GalacticGungan.json

Added GalacticGungan

---

pastes/WittyWalkingstick.json

Added Solder Paste T5
- WittyWalkingstick

Added WittyWalkingstick

---

inks/HungryHutt.json
pastes/RegalRabbit.json

Added
- HungryHutt Cond 3
- Regal Rabbit Sn63 Solder Paste

Added HungryHutt Cond 3 & RegalRabbit Lead SolderPaste

---

pastes/JauntyJunco.json
pastes/YareYehlSkipper.json

Added Solder Paste T5 
- YareYehlSkipper
Added Solder Paste T4
- JauntyJunco

Added Solder Paste T5 and T4
